Question 1. 

You are given two strings s and t. String t is generated by randomly
shuffling string s and then adding one more letter at a random position.
Return the letter that was added to t.

Examples

find_the_difference(&quot;abcd&quot;, &quot;abcde&quot;) ➞ &quot;e&quot;

find_the_difference(&quot;&quot;, &quot;y&quot;) ➞ &quot;y&quot;

find_the_difference(&quot;ae&quot;, &quot;aea&quot;) ➞ &quot;a&quot;

In [568]:
def find_the_difference(str_a, str_b):

#     str_a = "ae"
#     str_b = "aea"
    s1 = s2 = ""
    c = 0
    if len(str_a) > len(str_b):
        s1 = str_a
        s2 = str_b
    else:
        s1 = str_b
        s2 = str_a

    for i in (s1):
        if s1.count(i) != s2.count(i):
            print(i)
            break

In [569]:
find_the_difference("abcd", "abcde")

e

In [570]:
find_the_difference("", "y")

y

In [571]:
find_the_difference("ae", "aea")

a

In [579]:
def spot_the_diff(str_1, str_2):
    res = 0

    for i in range(len(str_1)):
        res = res ^ (ord)(str_1[i])
        print(res, str_1[i])

    for j in range(len(str_2)):
        res = res ^ (ord)(str_2[j])
        print(res, str_2[j])
    print("difference: ",(chr(res)))

In [580]:
spot_the_diff("abcd", "abcde")

97 a
3 b
96 c
4 d
101 a
7 b
100 c
0 d
101 e
difference:  e

In [581]:
spot_the_diff("", "y")

121 y
difference:  y

In [582]:
spot_the_diff("ae", "aea")

97 a
4 e
101 a
0 e
97 a
difference:  a

Question 2.

Given a function that accepts unlimited arguments, check and count how
many data types are in those arguments. Finally return the total in a list.
List order is:

[int, str, bool, list, tuple, dictionary]

Examples

count_datatypes(1, 45, &quot;Hi&quot;, False) ➞ [2, 1, 1, 0, 0, 0]

count_datatypes([10, 20], (&quot;t&quot;, &quot;Ok&quot;), 2, 3, 1) ➞ [3, 0, 0, 1, 1, 0]

count_datatypes(&quot;Hello&quot;, &quot;Bye&quot;, True, True, False, {&quot;1&quot;: &quot;One&quot;, &quot;2&quot;: &quot;Two&quot;}, [1,
3], {&quot;Brayan&quot;: 18}, 25, 23) ➞ [2, 2, 3, 1, 0, 2]

count_datatypes(4, 21, (&quot;ES&quot;, &quot;EN&quot;), (&quot;a&quot;, &quot;b&quot;), False, [1, 2, 3], [4, 5, 6]) ➞ [2,
0, 1, 2, 2, 0]

In [332]:
def count_datatypes(*data):
    int_ = str_ = bool_ = lst_ = tupl_  = dict_ = dtypes = 0
    lst1 = []

    for i in data:
        lst1.append(i)
    for i in lst1:
        if type(i) == int:
            int_ += 1
        elif type(i) == str:
            str_ += 1
        elif type(i) == bool:
            bool_ += 1
        elif type(i) == list:
            lst_+= 1
        elif type(i) == tuple:
            tupl_ += 1
        elif type(i) == dict:
            dict_ += 1
    dtypes = int_, str_, bool_, lst_, tupl_, dict_
    print(list(dtypes))

In [333]:
count_datatypes(1, 45, "Hi", False)

[2, 1, 1, 0, 0, 0]

In [334]:
count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1)

[3, 0, 0, 1, 1, 0]

In [335]:
count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1, 3], {"Brayan": 18}, 25, 23)

[2, 2, 3, 1, 0, 2]

In [336]:
count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6])

[2, 0, 1, 2, 2, 0]

In [383]:
def count_dtypes(*some_data):
    one_lst = []

    for i in some_data:
        one_lst.append(i)
        print(type(i))

    c_int =  list(map(type, one_lst)).count(int)
    c_str =  list(map(type, one_lst)).count(str)
    c_bool = list(map(type, one_lst)).count(bool)
    c_lst = list(map(type, one_lst)).count(list)
    c_tupl = list(map(type, one_lst)).count(tuple)
    c_dict = list(map(type, one_lst)).count(dict)

    coll_ = c_int, c_str, c_bool, c_lst, c_tupl, c_dict
    return list(coll_)

In [384]:
count_dtypes(1, 45, "Hi", False)

<class 'int'>
<class 'int'>
<class 'str'>
<class 'bool'>

[2, 1, 1, 0, 0, 0]

In [385]:
count_dtypes([10, 20], ("t", "Ok"), 2, 3, 1)

<class 'list'>
<class 'tuple'>
<class 'int'>
<class 'int'>
<class 'int'>

[3, 0, 0, 1, 1, 0]

In [386]:
count_dtypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1, 3], {"Brayan": 18}, 25, 23)

<class 'str'>
<class 'str'>
<class 'bool'>
<class 'bool'>
<class 'bool'>
<class 'dict'>
<class 'list'>
<class 'dict'>
<class 'int'>
<class 'int'>

[2, 2, 3, 1, 0, 2]

In [387]:
count_dtypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6])

<class 'int'>
<class 'int'>
<class 'tuple'>
<class 'tuple'>
<class 'bool'>
<class 'list'>
<class 'list'>

[2, 0, 1, 2, 2, 0]

Question 3. 

A Fibonacci string is a precedence of the Fibonacci series. It works with
any two characters of the English alphabet (as opposed to the numbers 0 and
1 in the Fibonacci series) 

as the initial items and concatenates them together
as it progresses in a similar fashion as the Fibonacci series.

Examples

fib_str(3, [&quot;j&quot;, &quot;h&quot;]) ➞ &quot;j, h, hj&quot;

fib_str(5, [&quot;e&quot;, &quot;a&quot;]) ➞ &quot;e, a, ae, aea, aeaae&quot;

fib_str(6, [&quot;n&quot;, &quot;k&quot;]) ➞ &quot;n, k, kn, knk, knkkn, knkknknk&quot;

In [449]:
def fib_str(num_, str_lst):
    
    first = str_lst[0]
    second = str_lst[1]
    count = 0
    temp = ""
    
    while count < num_:
        print(first)
        temp = second + first
        first = second
        second = temp
        count += 1

In [450]:
fib_str(5, ["e", "a"])

e
a
ae
aea
aeaae

In [451]:
fib_str(3, ["j", "h"])

j
h
hj

In [452]:
fib_str(6, ["n", "k"])

n
k
kn
knk
knkkn
knkknknk

Question 4. 

Given an integer between 0 and 26, make a variable (self.answer). That
variable would be assigned to a string in this format:

&quot;nines:your answer, threes:your answer, ones:your answer&quot;

You need to find out how many ones, threes, and nines it would at least take
for the number of each to add up to the given integer when multiplied by one,
three or nine (depends).

Examples

ones_threes_nines(10) ➞ &quot;nines:1, threes:0, ones:1&quot;

ones_threes_nines(15) ➞ &quot;nines:1, threes:2, ones:0&quot;

ones_threes_nines(22) ➞ &quot;nines:2, threes:1, ones:1&quot;

In [526]:
def ones_threes_nines(num):
    val = 0
    nines = []
    threes = []
    ones = []

    if num > 0 and num <= 26:
        val = num // 9
        nines.append(val)
        num = num - (val*9)
        val = num // 3
        threes.append(val)
        num = num - (val*3)
        ones.append(num) 
    else:
        print("Number should be more than 0 ")
    print("Nines: ", nines, "Threes: ", threes, "Ones : ", ones)

In [527]:
ones_threes_nines(10)

Nines:  [1] Threes:  [0] Ones :  [1]

In [514]:
ones_threes_nines(15)

Nines:  [1] Threes:  [2] Ones :  [0]

In [515]:
ones_threes_nines(22)

Nines:  [2] Threes:  [1] Ones :  [1]

In [516]:
def one_3_9(num):
    nines = num // 9
    threes = (num%9) // 3
    ones = num % 3
    
    print("Nines:", nines)
    print("Threes:", threes)
    print("Ones:", ones)

In [517]:
one_3_9(10)

Nines: 1
Threes: 0
Ones: 1

In [518]:
one_3_9(15)

Nines: 1
Threes: 2
Ones: 0

In [519]:
one_3_9(22)

Nines: 2
Threes: 1
Ones: 1

Question 5. 

The Fibonacci sequence is a classic use case for recursive functions since
the value of the sequence at a given index is dependent on the sum of the
last two values. 

However, the recursion tree created by solving the Fibonacci
sequence recursively can grow quite fast. 

Therefore it can be important to
think about the implications of running a function recursively. 

Depending on
the size of n needed and the capabilities of the system in question you might
want to take a different approach.

Write a non-recursive function that takes an integer n and returns the
Fibonacci sequence&#39;s value at index n.

Examples

fib(6) ➞ 8

0 + 1 = 1, 1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5, 3 + 5 = 8

fib(1) ➞ 1

fib(2) ➞ 1

In [549]:
def fib_val(num):
    a = 0
    b = 1
    temp = int()
    c = 0
    
    while c < num:
#         print(a)
        temp = a + b
        a = b
        b = temp
        c += 1
    print(a)

In [550]:
fib_val(6)

8

In [551]:
fib_val(1)

1

In [552]:
fib_val(2)

1

In [553]:
def fib(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, b+a
    return a

In [554]:
fib(6)

8

In [555]:
fib(1)

1

In [556]:
fib(2)

1

                                                    ################## THE END #####################